version: "3"

services:
  web:
    build: ${WEB_ROOT}
    command: ./command.sh
    volumes:
      - ${WEB_ROOT}/contracts:/code/web/contracts
      - ${WEB_ROOT}/migrations:/code/web/migrations
      - ${WEB_ROOT}/public:/code/web/public
      - ${WEB_ROOT}/src:/code/web/src
      - ${WEB_ROOT}/truffle.js:/code/web/truffle.js
      - ${WEB_ROOT}/package.json:/code/web/package.json
      - ${WEB_ROOT}/candidates.json:/code/web/candidates.json
    ports:
      - 3000:3000
    depends_on:
      - testrpc

  testrpc:
    build: ${WEB_ROOT}
    command: npm run network
    ports:
      - 8550:8550
    volumes:
      - ${WEB_ROOT}/contracts:/code/web/contracts
      - ${WEB_ROOT}/migrations:/code/web/migrations
      - ${WEB_ROOT}/public:/code/web/public
      - ${WEB_ROOT}/src:/code/web/src
      - ${WEB_ROOT}/truffle.js:/code/web/truffle.js
      - ${WEB_ROOT}/package.json:/code/web/package.json
      - ${WEB_ROOT}/candidates.json:/code/web/candidates.json
