version: "3"

services:
  web:
    build: web
    command: bash -c "npm run build && npm start"
    volumes:
      - ./web/contracts:/code/web/contracts
      - ./web/migrations:/code/web/migrations
      - ./web/public:/code/web/public
      - ./web/src:/code/web/src
      - ./web/truffle.js:/code/web/truffle.js
      - ./web/package.json:/code/web/package.json
      - ./web/candidates.json:/code/web/candidates.json
    ports:
      - 3000:3000
    depends_on:
      - testrpc

  testrpc:
    build: web
    command: npm run network
    ports:
      - 8550:8550
    volumes:
      - ./web/contracts:/code/web/contracts
      - ./web/migrations:/code/web/migrations
      - ./web/public:/code/web/public
      - ./web/src:/code/web/src
      - ./web/truffle.js:/code/web/truffle.js
      - ./web/package.json:/code/web/package.json
      - ./web/candidates.json:/code/web/candidates.json
