version: "3"

services:
  web:
    build: web
    command: bash -c "npm start"
    container_name: web
    volumes:
      - ./web:/code
    ports:
      - 3000:3000
    depends_on:
      - testrpc

  geth:
    build: geth
    command: npm run network
    container_name: testrpc
    ports:
      - 8550:8550
